#!/usr/bin/env python
# @create-shortcut-for-this

from duckietown_utils.cli import d8app_run
from duckietown_segmaps.cli import DisplayTileAndMaps


if __name__ == '__main__':
    d8app_run(DisplayTileAndMaps)
