#!/usr/bin/env python
# @create-shortcut-for-this

from duckietown_utils.cli import d8app_run
from complete_image_pipeline.on_logs import SingleImagePipelineLog


if __name__ == '__main__':
    d8app_run(SingleImagePipelineLog)
