#!/usr/bin/env python
from duckietown_utils.cli import d8app_run
from complete_image_pipeline.validate_calibration import ValidateCalibration


if __name__ == '__main__':
    d8app_run(ValidateCalibration)