use_stop_pose: True
num_waypoints: 5
visualization: True
speed: 0.3

canonical_goal_pose_right: {
  x: 0.2,
  y: -0.2,
  theta: -1.57,
}

canonical_goal_pose_left: {
  x: 0.4,
  y: 0.4,
  theta: 1.57,
}

canonical_goal_pose_straight: {
  x: 0.0,
  y: 0.6,
  theta: 0.0,
}

debug_dir: -1
