img_size: [240,320]
top_cutoff: 120

colors:
  WHITE:
    low: [0,0,150]
    high: [180,100,255]
  YELLOW:
    low: [0,100,100]
    high: [45,255,255]

line_detector_parameters:
  canny_thresholds: [80,200]
  canny_aperture_size: 3
  dilation_kernel_size: 3
  hough_threshold: 2
  hough_min_line_length: 3
  hough_max_line_gap: 1