# Initial state of the FSM

initial_state: "NORMAL_JOYSTICK_CONTROL"


events: # Maps from subscribing topic to signal ids
  joystick_override_on:
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: True
  joystick_override_off:
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: False
  obstacle_exists:
    topic: "avoiders/obstacle_exists"
    msg_type: "BoolStamped"
    trigger: True
  obstacle_cleared:
    topic: "avoiders/obstacle_exists"
    msg_type: "BoolStamped"
    trigger: False
  # intersection_comm_finish: 
  #   topic: "communicators/comm_status"
  #   msg_type: "BoolStamped"
  #   trigger: True 
  intersection_comm_start: 
    topic: "communicators/comm_status"
    msg_type: "BoolStamped"
    trigger: True 
  stop_line_detected:
    topic: "followers/stop_line_detector"
    msg_type: "BoolStamped"
    trigger: True 
  intersection_nav_start:
    topic: "navigators/intersection_nav_status"
    msg_type: "BoolStamped"
    trigger: True
  intersection_nav_finish:
    topic: "navigators/intersection_nav_status"
    msg_type: "BoolStamped"
    trigger: False

# Define nodes
nodes:
  decoder_node: "decoder_node/switch"
  anti_instagram: "anti_instagram_node/switch"
  static_object_detector_node: "static_object_detector_node/switch"
  line_detector_node: "line_detector_node/switch"
  lane_filter_node: "lane_filter_node/switch"
  framerate_high: "camera_node/framerate_high_switch"
  # extras added

  lane_controller_node: "lane_controller_node/switch"

  # Some of the nodes we have defined below have not been mapped yet. 
  # object_detection_node: "vehicle_filter_node/switch"
  # vehicle_avoidance_control_node: "vehicle_avoidance_control_node/switch"
  # vehicle_detection_node : "vehicle_detection_node/switch"

# Define state transitions

global_transitions:
  joystick_override_on: "NORMAL_JOYSTICK_CONTROL"
  joystick_override_off: "LANE_FOLLOWING"


states:
  NORMAL_JOYSTICK_CONTROL:
    active_nodes:
      - lane_filter_node
      - line_detector_node
      - stop_line_filter_node
      - framerate_high
      - decoder_node
    lights: ["joystick"]
    current_status: "implemented"
  LANE_FOLLOWING:
    transitions:
      obstacle_exists: "AVOID_OBSTACLE"
      stop_line_detected: "STOP_AT_INTERSECTION" # change name later
    active_nodes:
      - anti_instagram
      - decoder_node
      - line_detector_node
      - lane_filter_node
      - lane_controller_node
      ## Placeholders
      - object_detector_node 
      - object_avoider_node  
      # - vehicle_filter_node
      # - vehicle_detection_node
      # - vehicle_avoidance_control_node
    lights: ["lane_following"]
    current_status: "in_progress"
  STOP_AT_INTERSECTION:
    transitions:
      intersection_comm_start: "COMM_AT_INTERSECTION"
    active_nodes:
      - traffic_det_node 
      - stop_controller_node # Publish to  
  COMM_AT_INTERSECTION:
    transitions:
      # intersection_comm_finish: "NAVIGATE_INTERSECTION"
      intersection_nav_start: "NAVIGATE_INTERSECTION"
    active_nodes:
      - led_detection_node 
      - object_detector_node
      - communication_node # Does all the processing required for communication and priority allocation  
      - stop_controller_node 
  NAVIGATE_INTERSECTION: 
    transitions: 
      intersection_nav_finish: "LANE_FOLLOWING"
    active_nodes:
      - lane_filter_node 
      - deadreckoning_node
      - unicorn_intersection_node 
      - lane_controller_node 
  AVOID_OBSTACLE:
    transitions: 
      obstacle_cleared: "LANE_FOLLOWING"
    active_nodes: 
      - lane_filter_node
      - line_detector_node
      - object_detector_node 
      - avoid_obstacle_controller_node 


